
image:
  file: .devenv/Dockerfile

tasks:
  - name: setup
    before: |
      mkdir ~/.terraform.d
      if [[ $TF_CREDENTIALS_FILE_BASE64 != "" ]]; then
        echo $TF_CREDENTIALS_FILE_BASE64 | base64 -d | tee ~/.terraform.d/credentials.tfrc.json >> /dev/null
      fi
vscode:
  extensions:
    - hashicorp.terraform
    - tfsec.tfsec
